import images from '../../assets/images';

export const cardLoweredWidth = 115/2
export const cardLoweredHeight = 162/2
export const cards = [
    { id: 'LJ', rank: 1, value: 1, suit: 'J', suitInt: 4, image: images.card_back_green },
    { id: 'BJ', rank: 2, value: 2, suit: 'J', suitInt: 4, image: images.card_back_red },
    { id: 'AS', rank: 1, value: 14, suit: 'S', suitInt: 3, image: images.Card_Spade_Ace },
    { id: '2S', rank: 2, value: 2, suit: 'S', suitInt: 3, image: images.Card_Spade_2 },
    { id: '3S', rank: 3, value: 3, suit: 'S', suitInt: 3, image: images.Card_Spade_3 },
    { id: '4S', rank: 4, value: 4, suit: 'S', suitInt: 3, image: images.Card_Spade_4 },
    { id: '5S', rank: 5, value: 5, suit: 'S', suitInt: 3, image: images.Card_Spade_5 },
    { id: '6S', rank: 6, value: 6, suit: 'S', suitInt: 3, image: images.Card_Spade_6 },
    { id: '7S', rank: 7, value: 7, suit: 'S', suitInt: 3, image: images.Card_Spade_7 },
    { id: '8S', rank: 8, value: 8, suit: 'S', suitInt: 3, image: images.Card_Spade_8 },
    { id: '9S', rank: 9, value: 9, suit: 'S', suitInt: 3, image: images.Card_Spade_9 },
    { id: 'TS', rank: 10, value: 10, suit: 'S', suitInt: 3, image: images.Card_Spade_10 },
    { id: 'JS', rank: 11, value: 11, suit: 'S', suitInt: 3, image: images.Card_Spade_Jack },
    { id: 'QS', rank: 12, value: 12, suit: 'S', suitInt: 3, image: images.Card_Spade_Queen },
    { id: 'KS', rank: 13, value: 13, suit: 'S', suitInt: 3, image: images.Card_Spade_King },
    { id: 'AD', rank: 1, value: 14, suit: 'D', suitInt: 0, image: images.Card_Diamond_Ace },
    { id: '2D', rank: 2, value: 2, suit: 'D', suitInt: 0, image: images.Card_Diamond_2 },
    { id: '3D', rank: 3, value: 3, suit: 'D', suitInt: 0, image: images.Card_Diamond_3 },
    { id: '4D', rank: 4, value: 4, suit: 'D', suitInt: 0, image: images.Card_Diamond_4 },
    { id: '5D', rank: 5, value: 5, suit: 'D', suitInt: 0, image: images.Card_Diamond_5 },
    { id: '6D', rank: 6, value: 6, suit: 'D', suitInt: 0, image: images.Card_Diamond_6 },
    { id: '7D', rank: 7, value: 7, suit: 'D', suitInt: 0, image: images.Card_Diamond_7 },
    { id: '8D', rank: 8, value: 8, suit: 'D', suitInt: 0, image: images.Card_Diamond_8 },
    { id: '9D', rank: 9, value: 9, suit: 'D', suitInt: 0, image: images.Card_Diamond_9 },
    { id: 'TD', rank: 10, value: 10, suit: 'D', suitInt: 0, image: images.Card_Diamond_10 },
    { id: 'JD', rank: 11, value: 11, suit: 'D', suitInt: 0, image: images.Card_Diamond_Jack },
    { id: 'QD', rank: 12, value: 12, suit: 'D', suitInt: 0, image: images.Card_Diamond_Queen },
    { id: 'KD', rank: 13, value: 13, suit: 'D', suitInt: 0, image: images.Card_Diamond_King },
    { id: 'AC', rank: 1, value: 14, suit: 'C', suitInt: 1, image: images.Card_Club_Ace },
    { id: '2C', rank: 2, value: 2, suit: 'C', suitInt: 1, image: images.Card_Club_2 },
    { id: '3C', rank: 3, value: 3, suit: 'C', suitInt: 1, image: images.Card_Club_3 },
    { id: '4C', rank: 4, value: 4, suit: 'C', suitInt: 1, image: images.Card_Club_4 },
    { id: '5C', rank: 5, value: 5, suit: 'C', suitInt: 1, image: images.Card_Club_5 },
    { id: '6C', rank: 6, value: 6, suit: 'C', suitInt: 1, image: images.Card_Club_6 },
    { id: '7C', rank: 7, value: 7, suit: 'C', suitInt: 1, image: images.Card_Club_7 },
    { id: '8C', rank: 8, value: 8, suit: 'C', suitInt: 1, image: images.Card_Club_8 },
    { id: '9C', rank: 9, value: 9, suit: 'C', suitInt: 1, image: images.Card_Club_9 },
    { id: 'TC', rank: 10, value: 10, suit: 'C', suitInt: 1, image: images.Card_Club_10 },
    { id: 'JC', rank: 11, value: 11, suit: 'C', suitInt: 1, image: images.Card_Club_Jack },
    { id: 'QC', rank: 12, value: 12, suit: 'C', suitInt: 1, image: images.Card_Club_Queen },
    { id: 'KC', rank: 13, value: 13, suit: 'C', suitInt: 1, image: images.Card_Club_King },
    { id: 'AH', rank: 1, value: 14, suit: 'H', suitInt: 2, image: images.Card_Heart_Ace },
    { id: '2H', rank: 2, value: 2, suit: 'H', suitInt: 2, image: images.Card_Heart_2 },
    { id: '3H', rank: 3, value: 3, suit: 'H', suitInt: 2, image: images.Card_Heart_3 },
    { id: '4H', rank: 4, value: 4, suit: 'H', suitInt: 2, image: images.Card_Heart_4 },
    { id: '5H', rank: 5, value: 5, suit: 'H', suitInt: 2, image: images.Card_Heart_5 },
    { id: '6H', rank: 6, value: 6, suit: 'H', suitInt: 2, image: images.Card_Heart_6 },
    { id: '7H', rank: 7, value: 7, suit: 'H', suitInt: 2, image: images.Card_Heart_7 },
    { id: '8H', rank: 8, value: 8, suit: 'H', suitInt: 2, image: images.Card_Heart_8 },
    { id: '9H', rank: 9, value: 9, suit: 'H', suitInt: 2, image: images.Card_Heart_9 },
    { id: 'TH', rank: 10, value: 10, suit: 'H', suitInt: 2, image: images.Card_Heart_10 },
    { id: 'JH', rank: 11, value: 11, suit: 'H', suitInt: 2, image: images.Card_Heart_Jack },
    { id: 'QH', rank: 12, value: 12, suit: 'H', suitInt: 2, image: images.Card_Heart_Queen },
    { id: 'KH', rank: 13, value: 13, suit: 'H', suitInt: 2, image: images.Card_Heart_King }
]
